http:
  host: "0.0.0.0:20125"


mongodb:
  dsn: "mongodb://runnergo_open:czYNsm6LmfZ0XU3E@172.17.101.255:27017/runnergo_open?replicaSet=mgset-509843895"
  database: "runnergo_open"

kafka:
  host: "172.17.101.188:9092"
  topic: "runnergo"
  key: "kafka:report:partition"
  num: 10
  totalKafkaPartition: "TotalKafkaPartition"
  stressBelongPartition: "StressBelongPartition"

grpc:
  host: "kpcontroller.apipost.cn:443"

reportRedis:
  address: "172.17.101.191:6398"
  password: "apipost"
  db: 1

redis:
  address: "172.17.101.191:6398"
  password: "apipost"
  db: 1

log:
  path: "/data/logs/RunnerGo/RunnerGo-collector-info.log"

management:
  address: "https://manager.apipost.cc/management/api/v1/plan/notify_stop_stress"